# -*- coding: utf-8 -*-
# Text der fünf Akte der 3D-Fassung.
# Nicht die Kulturgeschichte, sondern das Produkt: eine Oberfläche, fünf Zustände.
S = {
"de": {"hint":"scrollen","skip":"Zum Inhalt springen",
 "e0":"Der Auszug","l0":"Alles steht darin. Gelesen wird es nicht.",
 "e1":"Der Blickwinkel","l1":"Dieselben Zahlen. Ein anderes Licht.",
 "e2":"Die Übersetzung","l2":"Aus zweihundert Zeilen wird ein Satz.",
 "n2":"Die Zahlen bleiben unverändert. Nur ihre Reihenfolge ändert sich.",
 "e3":"Drei Oberflächen","l3":"Ein Text. Als Reel, als Brief, als Edition.",
 "e4":"Zugestellt","l4":"Und dann wird er gelesen.",
 "r":["Auszug","Licht","Satz","Zustellung"]},
"fr": {"hint":"faites défiler","skip":"Aller au contenu",
 "e0":"Le relevé","l0":"Tout y figure. Personne ne le lit.",
 "e1":"L’angle","l1":"Les mêmes chiffres. Une autre lumière.",
 "e2":"La traduction","l2":"Deux cents lignes deviennent une phrase.",
 "n2":"Les chiffres ne changent pas. Seul leur ordre change.",
 "e3":"Trois surfaces","l3":"Un texte. En Reel, en Brief, en Edition.",
 "e4":"Remis","l4":"Et là, il est lu.",
 "r":["Relevé","Lumière","Phrase","Remise"]},
"it": {"hint":"scorri","skip":"Vai al contenuto",
 "e0":"L’estratto","l0":"C’è scritto tutto. Nessuno lo legge.",
 "e1":"L’angolazione","l1":"Gli stessi numeri. Un’altra luce.",
 "e2":"La traduzione","l2":"Duecento righe diventano una frase.",
 "n2":"I numeri restano gli stessi. Cambia solo il loro ordine.",
 "e3":"Tre superfici","l3":"Un testo. Come Reel, come Brief, come Edition.",
 "e4":"Consegnato","l4":"E allora viene letto.",
 "r":["Estratto","Luce","Frase","Consegna"]},
"en": {"hint":"scroll","skip":"Skip to content",
 "e0":"The statement","l0":"It is all in there. Nobody reads it.",
 "e1":"The angle","l1":"The same figures. A different light.",
 "e2":"The translation","l2":"Two hundred lines become one sentence.",
 "n2":"The numbers do not change. Only their order does.",
 "e3":"Three surfaces","l3":"One text. As Reel, as Brief, as Edition.",
 "e4":"Delivered","l4":"And then it gets read.",
 "r":["Statement","Light","Sentence","Delivery"]},
}
