# -*- coding: utf-8 -*-
# Der Text der fünf Akte, aus story.py übernommen.
S = {
"de": {"skip":"Erzählung überspringen",
 "e0":"vor vierzigtausend Jahren","l0":"Am Anfang sass jemand am Feuer und erzählte, was geschehen war.",
 "e1":"Uruk, 3400 v. Chr.","l1":"Die erste Schrift war keine Geschichte. Sie war eine Abrechnung über Gerste und Vieh.",
 "e2":"die folgenden fünftausend Jahre","l2":"Das Buch wurde immer genauer. Die Erzählung ging verloren.",
 "n2":"Venedig, 1494: die doppelte Buchführung bekommt ihre Grammatik.",
 "e3":"heute","l3":"Was bei Ihnen ankommt, ist genau, vollständig — und ungeöffnet.",
 "e4":"Tellingly","l4":"Wir setzen die beiden wieder zusammen.",
 "r":["40 000 v. Chr.","3400 v. Chr.","1494","heute"]},
"fr": {"skip":"Passer le récit",
 "e0":"il y a quarante mille ans","l0":"Au commencement, quelqu’un était assis près du feu et racontait ce qui s’était passé.",
 "e1":"Ourouk, 3400 av. J.-C.","l1":"La première écriture n’était pas un récit. C’était un décompte d’orge et de bétail.",
 "e2":"les cinq mille ans qui suivirent","l2":"Le registre est devenu toujours plus exact. Le récit s’est perdu.",
 "n2":"Venise, 1494 : la comptabilité en partie double reçoit sa grammaire.",
 "e3":"aujourd’hui","l3":"Ce qui vous parvient est exact, complet — et jamais ouvert.",
 "e4":"Tellingly","l4":"Nous remettons les deux ensemble.",
 "r":["40 000 av. J.-C.","3400 av. J.-C.","1494","aujourd’hui"]},
"it": {"skip":"Salta il racconto",
 "e0":"quarantamila anni fa","l0":"All’inizio qualcuno sedeva accanto al fuoco e raccontava che cosa era successo.",
 "e1":"Uruk, 3400 a.C.","l1":"La prima scrittura non era un racconto. Era un conteggio di orzo e bestiame.",
 "e2":"i cinquemila anni seguenti","l2":"Il registro è diventato sempre più esatto. Il racconto è andato perduto.",
 "n2":"Venezia, 1494: la partita doppia riceve la sua grammatica.",
 "e3":"oggi","l3":"Quello che le arriva è esatto, completo — e mai aperto.",
 "e4":"Tellingly","l4":"Rimettiamo insieme le due cose.",
 "r":["40 000 a.C.","3400 a.C.","1494","oggi"]},
"en": {"skip":"Skip the story",
 "e0":"forty thousand years ago","l0":"In the beginning someone sat by the fire and told what had happened.",
 "e1":"Uruk, 3400 BC","l1":"The first writing was not a story. It was a count of barley and cattle.",
 "e2":"the five thousand years that followed","l2":"The ledger grew ever more exact. The telling was lost.",
 "n2":"Venice, 1494: double-entry bookkeeping is given its grammar.",
 "e3":"today","l3":"What reaches you is exact, complete — and unopened.",
 "e4":"Tellingly","l4":"We put the two back together.",
 "r":["40,000 BC","3400 BC","1494","today"]},
}
